<a href="https://colab.research.google.com/github/Evertondecrespi/Numpy/blob/main/Mini_projeto_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='black'>Mini projeto Numpy</font>

### <font color='red'>Manipulando dados com Numpy</font>

<font color='blue'>Limpeza e Pré-Processamento de Dados com NumPy</font>

In [ ]:
# It shows the number of visitors who visited the central monuments between 2019 and 2021. ENG

# Mostra o número de visitantes que visitaram os monumentos centrais entre 2019 e 2021. PT

In [ ]:
# Dicionario de dados
"""Circle - City
Name of the Monument
Domestic-2019-2020: Number of people from India who visited the monument in 2019-20.
Foreign-2019-20: Number of foreigners who visited the monument in 2019-20.
Domestic-2020-21: Number of people from India who visited the monument in 2020-21.
Foreign-2020-2021: Number of foreigners who visited the monument in 2020-21.
% Growth 2021-21/2019-20-Domestic: Growth percentage of domestic visitors from 2019 to 2021.
% Growth 2021-21/2019-20-Foreign: Growth percentage of foreign visitors from 2019 to 2021."""

'Circle - City\nName of the Monument\nDomestic-2019-2020: Number of people from India who visited the monument in 2019-20.\nForeign-2019-20: Number of foreigners who visited the monument in 2019-20.\nDomestic-2020-21: Number of people from India who visited the monument in 2020-21.\nForeign-2020-2021: Number of foreigners who visited the monument in 2020-21.\n% Growth 2021-21/2019-20-Domestic: Growth percentage of domestic visitors from 2019 to 2021.\n% Growth 2021-21/2019-20-Foreign: Growth percentage of foreign visitors from 2019 to 2021.'

In [ ]:
# Import
import numpy as np

# Configuração de impressão do NumPy
np.set_printoptions(suppress = True, linewidth = 200, precision = 2)

### Carregando o dataset Turismo Indiano

In [ ]:
# Carrega as colunas do tipo string
df01 = np.genfromtxt("../data/India-Tourism.csv",
                            delimiter = ',',
                            skip_header = 1,
                            autostrip = True,
                            encoding = 'cp1252')
df01.view()                        

array([[        nan,         nan,  4429710.  , ...,     9034.  ,      -71.56,      -98.6 ],
       [        nan,         nan,  1627154.  , ...,     2810.  ,      -77.18,      -99.27],
       [        nan,         nan,   454376.  , ...,      574.  ,      -76.27,      -99.69],
       ...,
       [        nan,         nan,    22353.  , ...,       10.  ,      -54.28,      -88.24],
       [        nan,         nan,   262949.  , ...,      137.  ,      -55.84,      -86.41],
       [        nan,         nan, 43607075.  , ...,   415859.  ,      -69.84,      -84.91]])

### Tratando valores ausentes

In [ ]:
# Observe como várias colunas estão com o tipo nan. 
# Isso se deve a caracteres especiais no conjunto de dados e a forma como o NumPy carrega dados numéricos e do tipo string. Vamos resolver isso.
np.isnan(df01).sum()

357

In [ ]:
# Vamos retornar o maior valor + 1 ignorando valores nan
# Usaremos esse valor arbitrário para preencher os valores ausentes no momento da carga de dados de variáveis
# numéricas e depois tratamos esse valor como valor ausente
valor_nulo = np.nanmax(df01) + 1
print(valor_nulo)

43607076.0


In [ ]:
# Calculamos a média (variáveis numéricas) ignorando valores nan por coluna
# Usaremos isso para separar variáveis numéricas de variáveis do tipo string
media_ignorando_nan = np.nanmean(df01, axis = 0)
print(media_ignorando_nan)

[      nan       nan 738855.89  46715.37 222604.64   7043.55    -28.57    942.88]


/tmp/ipykernel_2127/1630894391.py:3: RuntimeWarning: Mean of empty slice
  media_ignorando_nan = np.nanmean(df01, axis = 0)


In [ ]:
# Separando colunas do tipo string com valores ausentes
colunas_strings = np.argwhere(np.isnan(media_ignorando_nan)).squeeze()
colunas_strings

array([0, 1])

In [ ]:
# Separando as colunas numéricas 
colunas_numericas = np.argwhere(np.isnan(media_ignorando_nan) == False).squeeze()
colunas_numericas

array([2, 3, 4, 5, 6, 7])

### Carregando o dataset Turismo Indiano - Somente string

In [ ]:
# Carrega novamente os dados das colunas do tipo string
strings = np.genfromtxt("../data/India-Tourism.csv",
                            delimiter = ',',
                            skip_header = 1,
                            autostrip = True, 
                            usecols = colunas_strings,
                            dtype = str, 
                            encoding = 'cp1252')
strings

array([['Agra', 'Taj Mahal'],
       ['Agra', 'Agra Fort'],
       ['Agra', 'Fatehpur Sikri'],
       ['Agra', 'Akbar Tomb Sikandra'],
       ['Agra', 'Mariam tomb Sikandra'],
       ['Agra', 'Itimad-ud-Daulah-Tomb'],
       ['Agra', 'Ram Bagh'],
       ['Agra', 'Mehtab Bagh'],
       ['Agra', 'Mausoleum'],
       ['Total', 'Total'],
       ['Lucknow', 'Site of Sahet mahet'],
       ['Lucknow', 'Residency Building'],
       ['Lucknow', 'Piprahwa & Ganwaria'],
       ['Total', 'Total'],
       ['Jhansi', '"Gupta Temple & Varah Temple Deogarh"'],
       ['Jhansi', 'Kalinjar Fort'],
       ['Jhansi', 'Rani Lakshmi Bai Mahal'],
       ['Jhansi', 'Rani Jhansi Fort'],
       ['Total', 'Total'],
       ['Sarnath', 'Lord Cornwallis Tomb'],
       ['Sarnath', '"Old Fort (Shahi Fort) Jaunpur"'],
       ['Sarnath', 'Observatory of Man Singh'],
       ['Sarnath', 'Excavated Remains at sarnath'],
       ['Sarnath', 'Tomb of Lal Khan'],
       ['Sarnath', 'Ancient Buddhist Site known as Chaukhandi s

### Carregando o dataset Turismo Indiano - Somente Numerico

In [ ]:
# Carrega as colunas do tipo numérico preenchendo os valores ausentes
numeric = np.genfromtxt("../data/India-Tourism.csv",
                            delimiter = ',',
                            autostrip = True,
                            skip_header = 1,
                            usecols = colunas_numericas,
                            filling_values = valor_nulo, 
                            encoding = 'cp1252')
numeric

array([[ 4429710.  ,   645415.  ,  1259892.  ,     9034.  ,      -71.56,      -98.6 ],
       [ 1627154.  ,   386522.  ,   371242.  ,     2810.  ,      -77.18,      -99.27],
       [  454376.  ,   184751.  ,   107835.  ,      574.  ,      -76.27,      -99.69],
       ...,
       [   22353.  ,       85.  ,    10219.  ,       10.  ,      -54.28,      -88.24],
       [  262949.  ,     1008.  ,   116120.  ,      137.  ,      -55.84,      -86.41],
       [43607075.  ,  2756561.  , 13153076.  ,   415859.  ,      -69.84,      -84.91]])

### Carregando o dataset Turismo Indiano - Somente nome das colunas

In [ ]:
# Carrega os nomes das colunas
arr_nomes_colunas = np.genfromtxt("../data/India-Tourism.csv",
                                  delimiter = ',',
                                  autostrip = True,
                                  skip_footer = df01.shape[0],
                                  dtype = str, 
                                  encoding = 'cp1252')
arr_nomes_colunas

array(['Circle', 'Name of the Monument', 'Domestic-2019-20', 'Foreign-2019-20', 'Domestic-2020-21', 'Foreign-2020-21', 'Growth 2021-21/2019-20-Domestic', 'Growth 2021-21/2019-20-Foreign'],
      dtype='<U31')

In [ ]:
# Separa cabeçalho de colunas numéricas e string
header_strings, header_numeric = arr_nomes_colunas[colunas_strings], arr_nomes_colunas[colunas_numericas]
header_strings, header_numeric

(array(['Circle', 'Name of the Monument'], dtype='<U31'),
 array(['Domestic-2019-20', 'Foreign-2019-20', 'Domestic-2020-21', 'Foreign-2020-21', 'Growth 2021-21/2019-20-Domestic', 'Growth 2021-21/2019-20-Foreign'], dtype='<U31'))

### Renomando as colunas

In [ ]:
# Vamos ajustar o nome das colunas para facilitar a identificação
header_strings[0] = "Cidade"
header_strings[1] = "Monumento"
header_strings

array(['Cidade', 'Monumento'], dtype='<U31')

In [ ]:
# Vamos ajustar o nome das colunas para facilitar a identificação
header_numeric[0] = 

SyntaxError: invalid syntax (503628745.py, line 2)

### Pré-Processamento da Variável cidade com Label Encoding

In [ ]:
# Extrai os valores únicos da variável
np.unique(strings[:,0])

array(['Agra', 'Amaravati', 'Aurangabad', 'Banglore', 'Bhopal', 'Bhubaneswar', 'Chandigarh', 'Chennai', 'Delhi', 'Dharwad', 'Goa', 'Grand Total', 'Guwahati', 'Hampi', 'Hyderabad', 'Jabalpur',
       'Jaipur', 'Jhansi', 'Jodhpur', 'Kolkata', 'Leh', 'Lucknow', 'Mumbai', 'Nagpur', 'Patna', 'Raiganj', 'Raipur', 'Rajkot', 'Sarnath', 'Shimla', 'Srinagar', 'Thrissur', 'Tiruchirappalli', 'Total',
       'Vadodara'], dtype='<U110')

In [ ]:
# Mostra a quantidade de valores unicos 
cidades_numero = np.unique(strings[:,0])
cidades_numero.shape

(35,)

In [ ]:
# Criamos um array com os meses (incluindo um elemento como vazio para o que estiver em branco)
cidades = np.array(['Agra', 'Amaravati', 'Aurangabad', 'Banglore', 'Bhopal', 'Bhubaneswar', 'Chandigarh', 'Chennai', 'Delhi', 'Dharwad', 'Goa', 'Grand Total', 'Guwahati', 'Hampi', 'Hyderabad', 'Jabalpur',
       'Jaipur', 'Jhansi', 'Jodhpur', 'Kolkata', 'Leh', 'Lucknow', 'Mumbai', 'Nagpur', 'Patna', 'Raiganj', 'Raipur', 'Rajkot', 'Sarnath', 'Shimla', 'Srinagar', 'Thrissur', 'Tiruchirappalli', 'Total',
       'Vadodara'])

In [ ]:
# Loop para converter os nomes das cidades em valores numéricos
# Chamamos isso de label encoding
for i in range(35):
        strings[:,0] = np.where(strings[:,0] == cidades[i], i, strings[:,0])
strings[:,0]        

array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '33', '21', '21', '21', '33', '17', '17', '17', '17', '33', '28', '28', '28', '28', '28', '28', '33', '31', '31', '31', '31', '33', '7', '7', '7',
       '33', '32', '32', '32', '32', '32', '32', '32', '33', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '33', '15', '15', '15', '33', '9', '9', '9', '9', '9', '9', '33', '13', '13', '33',
       '3', '3', '3', '3', '33', '25', '25', '33', '19', '19', '33', '27', '27', '27', '33', '34', '34', '34', '34', '33', '5', '5', '5', '5', '5', '33', '2', '2', '2', '2', '2', '2', '33', '22',
       '22', '22', '22', '22', '22', '22', '22', '22', '22', '22', '22', '22', '33', '23', '23', '33', '6', '6', '33', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '33', '12', '12', '12',
       '12', '12', '33', '10', '33', '14', '14', '14', '33', '16', '16', '16', '33', '18', '18', '18', '33', '20', '33', '24', '24', '24', '24', '24', '33', '26', '33', '29', '29', '33', '30', '30',
       '

In [ ]:
# Extrai os valores únicos da variável
np.unique(strings[:,1])

array(['"Ancient Buddhist Remains comprising monastery stupa rock sculptures inscriptions ect Mansur"', '"Ancient Site and Adamgrah rock shelter Kalamdi Rasuliya and kishanpur"',
       '"Ancient site of Vaishali Kolhua"', '"Asokan Rock Edict Jungadh"', '"Avantiswamin Temple Avantipur District Pulwama"', '"Baba Pyara Caves Junagadh & Khapra Khodiya Caves Junagadh"',
       '"Badal Mahal Gatwway Chanderi"', '"Bekal Fort Pallikkare Distt. Kasargod"', '"Buddhish Caves Junagadh"', '"Buddhist Monuments Sanchi"',
       '"Buddhist Remains on hill top at Guntupalli W.G.District"', '"Buddhist cave no 01 to 51 Dhamnar Tehsil Garoth"', '"Cave Temple & Inscriptions Bhaja"',
       '"Cave Temple and Inscriptions Junaar Lenyadri"', '"Caves Temples and inscriptions Karla"', '"Champaner Monuments Pavagadh"', '"Fort Museum Thirumayam"', '"Fort Palakkad Palakkad"',
       '"Fort St. Angelo Kannur"', '"Fort on Rock Dindigual"', '"Gingee Fort Gingee"', '"Gol Gumbaz Vijayapura"', '"Group of Monuments Hamp

In [ ]:
# Mostra a quantidade de valores unicos 
monumento_numero = np.unique(strings[:,1])
monumento_numero.shape

(146,)

In [ ]:
monumento  = np.array(['"Ancient Buddhist Remains comprising monastery stupa rock sculptures inscriptions ect Mansur"', '"Ancient Site and Adamgrah rock shelter Kalamdi Rasuliya and kishanpur"',
       '"Ancient site of Vaishali Kolhua"', '"Asokan Rock Edict Jungadh"', '"Avantiswamin Temple Avantipur District Pulwama"', '"Baba Pyara Caves Junagadh & Khapra Khodiya Caves Junagadh"',
       '"Badal Mahal Gatwway Chanderi"', '"Bekal Fort Pallikkare Distt. Kasargod"', '"Buddhish Caves Junagadh"', '"Buddhist Monuments Sanchi"',
       '"Buddhist Remains on hill top at Guntupalli W.G.District"', '"Buddhist cave no 01 to 51 Dhamnar Tehsil Garoth"', '"Cave Temple & Inscriptions Bhaja"',
       '"Cave Temple and Inscriptions Junaar Lenyadri"', '"Caves Temples and inscriptions Karla"', '"Champaner Monuments Pavagadh"', '"Fort Museum Thirumayam"', '"Fort Palakkad Palakkad"',
       '"Fort St. Angelo Kannur"', '"Fort on Rock Dindigual"', '"Gingee Fort Gingee"', '"Gol Gumbaz Vijayapura"', '"Group of Monuments Hampi"',
       '"Group of Temple Parameshvar shiv and Karan Temple Amarkantak"', '"Group of Temples at kiramchi District Udhampur"', '"Group of four MaidansCharaideo Sibasagar"',
       '"Group of monument Royal Palace Mandu"', '"Gupta Temple & Varah Temple Deogarh"', '"Ibrahim Rauza Bijapur"', '"Jaina & Vaishnava Cave Badami"', '"Janjira Fort Murd"',
       '"Kareghar of Ahom Kings Sibasagar"', '"Kolaba Fort Alibag"', '"Moovarkoil Kodumbalur"', '"Natural Caven with inscription eladipattam Sittannavasal"', '"Old Fort (Shahi Fort) Jaunpur"',
       '"Old Fort Sholapur"', '"Palace Complex at Ramnagar Distt. Udhampur"', '"Ranghar Pavillion Jaisagar"', '"Rani Ki-Vav Patan"', '"Remains of Patliputra Site of Mauryan Palace Kumrahar"',
       '"Rock-cut Jain Temple Sittannavasasl"', '"Rudabai Step Well Adalaj"', '"Ruined Fort kangra"', '"Sun Temple Konark"', '"Sun temple Modhera"', '"Temples & Sculpture Shed lakkumdi"',
       '"The palace situated in the fort Burhanpur"', '"Tiger headed Rock cut temple & two other monuments Saluvankuppam"', '"Western Group of Temples Khajuraho"', 'Aga  Khan Palace Building',
       'Agra Fort', "Ahom Raja's Palace", 'Ajanta Caves', 'Akbar Tomb Sikandra', 'Amaravati mahastupa', 'Ancient Buddhist Site known as Chaukhandi stupa', 'Ancient Palace Leh',
       'Ancient Remains on both Udaigiri & Khandagiri Hills', 'Ancient Site Bhangarh', 'Ancient Site of Vikramshila Antichak', 'Aurangabad Caves', 'Baori at Abhaneri', 'Bellary Fort',
       'Bir Singh Palace Datia', 'Bishnudol', 'Bishnupur Temples', 'Buddhist Caves', 'Buddhist Caves Kanheri', 'Caves 1 t0 20 Udaygiri Vidisha', 'Chandragiri Monument', 'Charminar',
       'Chittaurgarh Fort', 'Cooch Bihar Palace', 'Dariya Daulath Bagh', 'Daulatabad Fort', 'Deeg Bhawan', 'Durga temple complex Aihole', 'Elephanta Caves', 'Ellora Caves',
       'Excavated Remains at Nalanda', 'Excavated Remains at sarnath', 'Fatehpur Sikri', 'Fort Vattakottai', 'Fortress and Temple Chitrudurga Fort', 'Gawilgarh Fort', 'Golconda', 'Grand Total',
       'Group of Monuments (WH) Pattadakal', 'Group of Monuments Mamallapuram', 'Gwalior Fort', 'Hauzkhas', 'Hazarduari Palace', "Hoshang Shah's Tomb", 'Humayun Tomb', 'Itimad-ud-Daulah-Tomb',
       'Jantar Mantar', 'Kalinjar Fort', 'Keshava Temple', 'Khan-I-Khana', 'Kondiote Caves', 'Kotla Feroz Shah', 'Kumbhalgarh Fort', 'Lohgad Fort', 'Lord Cornwallis Tomb',
       'Marble Pavillion and balustrade on the Ana Sagar bund and ruins of the marble Hammam Behind the Ana sagar Bund', 'Mariam tomb Sikandra', 'Mausoleum', 'Mehtab Bagh', 'Metcelf-Hall',
       'Nagarjuna Kunda', 'Observatory of Man Singh', 'Palace of Tipu Sultan', 'Pandulena Caves', 'Piprahwa & Ganwaria', 'Purana Qila', 'Qutub Minar', 'Raigad Fort', 'Rajarani Temple', 'Ram Bagh',
       'Rani Jhansi Fort', 'Rani Lakshmi Bai Mahal', 'Red Fort', 'Residency Building', 'Rock-cut Temples and Sculptures', "Roopmati's Pavilion", 'Ruins of Buddhist Temples and Images lalitgiri',
       'Safdarjung Tomb', 'Shaniwarwada', "Sheikh Chilli's Tomb", "Sher Shah's Tomb", 'Site of Sahet mahet', 'Sultanghari Tomb', 'Suraj Kund', 'Taj Mahal',
       'Temple of Laxman and Old sites including sculptures sirpur', 'The Hill Containing Many Valuable Sculptures and Images Ratnagiri', "Tirumalai Nayak's Palace Srivilliputhur",
       'Tomb of Lal Khan', 'Tomb of Rabia Durani (Bibi ka Maqbara)', 'Total', 'Tughluqabad', 'Undavalli caves', 'Upper Fort Aguada', 'Warangal', 'mattancherry Palace Museum Kochi'])

In [ ]:
# Loop para converter os nomes dos monumentos em valores numéricos
# Chamamos isso de label encoding
for i in range(146):
        strings[:,1] = np.where(strings[:,1] == monumento[i], i, strings[:,1])
strings[:,1]  

array(['134', '51', '82', '54', '106', '95', '119', '108', '107', '140', '131', '123', '114', '140', '27', '97', '121', '120', '140', '104', '35', '111', '81', '138', '56', '140', '7', '145', '17',
       '18', '140', '89', '20', '140', '19', '33', '41', '137', '34', '16', '83', '140', '67', '47', '93', '26', '125', '9', '90', '11', '6', '69', '64', '140', '1', '49', '23', '140', '77', '29',
       '88', '21', '28', '46', '140', '22', '63', '140', '74', '98', '112', '84', '140', '73', '92', '140', '66', '109', '140', '3', '8', '5', '140', '15', '45', '39', '42', '140', '44', '58', '118',
       '136', '126', '140', '53', '79', '139', '75', '113', '61', '140', '78', '68', '128', '50', '13', '14', '12', '117', '32', '36', '30', '100', '103', '140', '85', '0', '140', '133', '129',
       '140', '99', '132', '141', '122', '94', '116', '91', '96', '127', '101', '115', '140', '52', '31', '38', '65', '25', '140', '143', '140', '71', '86', '144', '140', '59', '62', '76', '140',
       '72', '1